Repository 7th-Mile/trip-for-p, pull requests merged in 2024-09, with the labels that each got.

#136 [#104] ✨ feat: 스프링 시큐리티 회원가입 구현
  build.gradle
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/UserDto.java
  src/main/java/team/seventhmile/tripforp/domain/user/repository/UserRepository.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
  src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java
  src/main/java/team/seventhmile/tripforp/global/config/WebConfig.java
  src/main/java/team/seventhmile/tripforp/global/exception/user/AlreadyUsedEmailException.java
  src/main/java/team/seventhmile/tripforp/global/exception/user/UserExceptionHandler.java
  src/main/java/team/seventhmile/tripforp/global/exception/user/UserRegistrationException.java
  src/main/java/team/seventhmile/tripforp/global/exception/user/WithdrawnUserException.java
  src/test/java/team/seventhmile/tripforp/domain/user/controller/UserControllerTest.java
  src/test/java/team/seventhmile/tripforp/domain/user/repository/UserRepositoryTest.java
  src/test/java/team/seventhmile/tripforp/domain/user/service/UserServiceTest.java
Labels: feature

#135 [#134] ✨doc: 자유게시판 서비스 수정
  src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
Labels: documentation

#152 [#149] :bug: fix: 여행 코스 목록 조회 안되는 오류 수정
  src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
  src/main/java/team/seventhmile/tripforp/domain/plan/dto/GetPlanListResponse.java
  src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryCustom.java
  src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepositoryImpl.java
  src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanService.java
Labels: bug

#153 [#137] ✨ feat: 스프링 시큐리티 로그인 구현 및 jwt 토큰 발급
  build.gradle
  src/main/java/team/seventhmile/tripforp/domain/user/service/CustomUserDetails.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/CustomUserDetailsService.java
  src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java
  src/main/java/team/seventhmile/tripforp/global/jwt/JwtFilter.java
  src/main/java/team/seventhmile/tripforp/global/jwt/JwtUtil.java
  src/main/java/team/seventhmile/tripforp/global/jwt/LoginFilter.java
Labels: feature

#156 [#145] ✨ feat: 로그인, 회원가입 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/index.js
  frontend/src/api/interceptor.js
  frontend/src/assets/biglogo.png
  frontend/src/assets/email.png
  frontend/src/assets/nickname.png
  frontend/src/assets/password.png
  frontend/src/assets/signup.png
  frontend/src/components/HeaderComponent.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/store/index.js
  frontend/src/views/LayoutView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/MypageView.vue
  frontend/src/views/SignupView.vue
Labels: feature

#138 [#133]👷 CI/CD:workflow 작성
  .github/workflows/ci-cd.yml
Labels: CI/CD

#159 [#154] ✨ feat: JWT Refresh 토큰 발급
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java
  src/main/java/team/seventhmile/tripforp/global/jwt/JwtFilter.java
  src/main/java/team/seventhmile/tripforp/global/jwt/JwtUtil.java
  src/main/java/team/seventhmile/tripforp/global/jwt/LoginFilter.java
Labels: feature

#151 [#146] ✨feat: 매거진 첨부파일 기능 구현
  src/main/java/team/seventhmile/tripforp/domain/file/controller/FileController.java
  src/main/java/team/seventhmile/tripforp/domain/file/dto/FileDto.java
  src/main/java/team/seventhmile/tripforp/domain/file/entity/File.java
  src/main/java/team/seventhmile/tripforp/domain/file/repository/FileRepository.java
  src/main/java/team/seventhmile/tripforp/domain/file/service/FileService.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepository.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java
Labels: feature, documentation

#169 Feat/#161 CI/CD Spring yml파일 추가
  .github/workflows/ci-cd.yml
Labels: CI/CD

#172 [#171] ✨feat: 리뷰 게시판 전체 수정
  src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/dto/ReviewPostDto.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewPost.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepository.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
Labels: feature, documentation

#178 [#160] ✨ feat: JWT Refresh 토큰 redis 저장 구현
  src/main/java/team/seventhmile/tripforp/domain/user/service/TokenService.java
  src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java
  src/main/java/team/seventhmile/tripforp/global/jwt/JwtUtil.java
  src/main/java/team/seventhmile/tripforp/global/jwt/LoginFilter.java
Labels: feature

#181 [#179] 🐛 Fix : RedisConfig의 RedisTemplate 통일화
  src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/TokenService.java
  src/main/java/team/seventhmile/tripforp/global/config/RedisConfig.java
Labels: bug, refactor

#189 [#188] ✨bug: 리뷰 게시판 전체 수정
  src/main/java/team/seventhmile/tripforp/domain/file/entity/File.java
  src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanRepository.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/dto/ReviewPostDto.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewFile.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewPost.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepository.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryCustom.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryImpl.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
Labels: bug, documentation

#201 [#191] ✨ Feat : 회원가입 이메일 인증 기능 추가
  frontend/src/api/index.js
  frontend/src/views/SignupView.vue
  src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/EmailCodeResponse.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
  src/main/java/team/seventhmile/tripforp/global/exception/AuthCustomException.java
  src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java
  src/main/java/team/seventhmile/tripforp/global/exception/GlobalExceptionHandler.java
Labels: refactor

#200 [#184] ✨ Feat : 로그아웃 구현
  src/main/java/team/seventhmile/tripforp/domain/user/entity/User.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/TokenService.java
  src/main/java/team/seventhmile/tripforp/global/jwt/CustomLogoutFilter.java
Labels: feature

#199 [#198] ✨bug: 리뷰 게시판 최종 수정
  src/main/java/team/seventhmile/tripforp/domain/file/entity/File.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewFile.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewPost.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
Labels: bug

#208 [#207] 🐛 Fix : LogoutFilter 추가
  src/main/java/team/seventhmile/tripforp/global/config/SecurityConfig.java
Labels: bug

#209 [#205] ✨fix: 회원가입 예외처리 수정
  frontend/src/api/index.js
  frontend/src/views/SignupView.vue
  src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/ApiResponse.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
  src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java
Labels: feature

#211 [#210] ✨Refactor: 회원가입 불필요 코드 & 주석 수정
  frontend/src/views/SignupView.vue
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/entity/User.java
Labels: refactor

#214 [#204] ✨Feat: 회원가입(FE) 닉네임 중복 검사 구현
  frontend/src/api/index.js
  frontend/src/views/SignupView.vue
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
  src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java
Labels: feature

#218 [#215] ✨Feat: 개인정보조회 BE(마이페이지) 구현
  src/main/java/team/seventhmile/tripforp/domain/user/controller/MyPageController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/UserInfoResponse.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/MyPageService.java
  src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java
Labels: feature

#222 [#206] ✨ Feat : 비밀번호 변경 구현
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/ModifyPasswordRequest.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
  src/main/java/team/seventhmile/tripforp/global/exception/ErrorCode.java
Labels: feature

#226 [#221] ✨Feat: 개인정보수정 BE(마이페이지) 구현
  src/main/java/team/seventhmile/tripforp/domain/user/controller/MyPageController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/UserInfoRequest.java
  src/main/java/team/seventhmile/tripforp/domain/user/entity/User.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/MyPageService.java
Labels: feature

#227 [#224] ♻️ Refactor : 비밀번호 변경 로직 전체적인 리팩토링
  src/main/java/team/seventhmile/tripforp/domain/user/controller/MyPageController.java
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/MyPageService.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
Labels: refactor

#230 [#229] 🐛 Fix : MyPage 충돌 해결 후 에러 수정
  src/main/java/team/seventhmile/tripforp/domain/user/controller/MyPageController.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/MyPageService.java
Labels: bug

#213 [#212] ✨bug: 매거진 게시판 최종 수정
  src/main/java/team/seventhmile/tripforp/domain/file/entity/File.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/dto/MagazineDto.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepository.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepositoryCustom.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/repository/MagazineRepositoryImpl.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java
Labels: bug, documentation

#235 [#234] ♻️ Refactor : MyPage -> User 로직 이동 리팩토링
  src/main/java/team/seventhmile/tripforp/domain/user/controller/MyPageController.java
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/MyPageService.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
Labels: refactor

#236 [#232] :construction_worker: CI/CD: 배포 버전 CI/CD 파이프라인 구축
  .github/workflows/main-ci-cd.yml
Labels: CI/CD

#244 [#231] ✨ Feat : 비밀번호 찾기 시 비밀번호 재설정 로직 구현
  src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/FindPasswordRequest.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
Labels: feature

#247 [#237] ✨Feat: 회원 탈퇴 기능(BE) 구현
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/entity/User.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
Labels: feature

#252 [#243] ✨ Fix: 마이페이지 개인정보 조회 및 수정 API 수정
  frontend/src/api/index.js
  frontend/src/components/UpdateInfo.vue
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
  src/main/java/team/seventhmile/tripforp/global/config/WebConfig.java
Labels: feature

#254 [#253] 🐛 Fix : 회원가입 API 수정
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
Labels: refactor

#266 [#259] ✨ Feat: 마이페이지 작성/댓글/좋아요 글 목록 조회 API 구현
  src/main/java/team/seventhmile/tripforp/domain/free_comment/controller/FreeCommentController.java
  src/main/java/team/seventhmile/tripforp/domain/free_comment/dto/FreeCommentDto.java
  src/main/java/team/seventhmile/tripforp/domain/free_comment/repository/FreeCommentRepository.java
  src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/controller/FreePostController.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepository.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
  src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanController.java
  src/main/java/team/seventhmile/tripforp/domain/plan/controller/PlanLikeController.java
  src/main/java/team/seventhmile/tripforp/domain/plan/dto/CreatePlanRequest.java
  src/main/java/team/seventhmile/tripforp/domain/plan/repository/PlanLikeRepository.java
  src/main/java/team/seventhmile/tripforp/domain/plan/service/PlanLikeService.java
  src/main/java/team/seventhmile/tripforp/domain/review_comment/controller/ReviewCommentController.java
  src/main/java/team/seventhmile/tripforp/domain/review_comment/dto/ReviewCommentDto.java
  src/main/java/team/seventhmile/tripforp/domain/review_comment/repository/ReviewCommentRepository.java
  src/main/java/team/seventhmile/tripforp/domain/review_comment/service/ReviewCommentService.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/controller/ReviewPostController.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryCustom.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryImpl.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
Labels: feature

#272 [#267] :sparkles: Feat: 비밀번호 재설정 화면 구현 및 API 연결
  frontend/src/api/index.js
  frontend/src/router/index.js
  frontend/src/views/LayoutView.vue
  frontend/src/views/LoginView.vue
  frontend/src/views/ResetPasswordView.vue
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
Labels: feature

#273 [#271] ♻️ Refactor : EmailService 중복 코드 리팩토링
  src/main/java/team/seventhmile/tripforp/domain/user/service/EmailService.java
Labels: refactor

#280 [#274] :sparkles: Feat: 마이페이지 작성한 글 목록 조회 화면 구현
  frontend/src/api/index.js
  frontend/src/components/MyFreePosts.vue
  frontend/src/components/MyReviewPosts.vue
  frontend/src/views/MypageView.vue
  src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepository.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
Labels: feature

#286 [#271] 🐛 Fix : 탈퇴한 사용자가 로그인 되는 문제 해결
  src/main/java/team/seventhmile/tripforp/domain/user/service/CustomUserDetailsService.java
Labels: bug

#270 [#262] ✨ Feat : Alan 해당 지역에서 할 수 있는 여행 추천 API
  src/main/java/team/seventhmile/tripforp/external/alan/controller/AlanApiController.java
  src/main/java/team/seventhmile/tripforp/external/alan/dto/AreaRecsRequest.java
  src/main/java/team/seventhmile/tripforp/external/alan/service/AlanApiService.java
Labels: feature

#293 [#290] ✨ Feat : user validation 추가
  src/main/java/team/seventhmile/tripforp/domain/user/controller/EmailController.java
  src/main/java/team/seventhmile/tripforp/domain/user/controller/UserController.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/EmailCodeRequest.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/FindPasswordRequest.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/ModifyPasswordRequest.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/UserDto.java
  src/main/java/team/seventhmile/tripforp/domain/user/dto/UserInfoRequest.java
Labels: feature

#299 [#297] :construction_worker: ci/cd develop 브랜치 버전 삭제
  .github/workflows/ci-cd.yml
Labels: CI/CD

#309 [#308] :necktie: 개인정보수정 로직 변경
  build.gradle
  frontend/src/components/UpdateInfo.vue
  src/main/java/team/seventhmile/tripforp/domain/user/dto/UserInfoRequest.java
  src/main/java/team/seventhmile/tripforp/domain/user/service/UserService.java
Labels: feature
