Repository 7th-Mile/trip-for-p, pull requests merged in 2024-08, with the labels that each got.

#34 [#31] ✨feat: 매거진 엔티티 수정
  src/main/java/team/seventhmile/tripforp/magazine/entity.java
Labels: feature

#37 [#36] ✨feat: 매거진 DTO 생성
  src/main/java/team/seventhmile/tripforp/magazine/Dto.java
Labels: feature

#38 [#30]✨ feat: User Entity 개발
  src/main/java/team/seventhmile/tripforp/domain/user/entity/Role.java
  src/main/java/team/seventhmile/tripforp/domain/user/entity/User.java
Labels: feature

#42 [#41] ✨feat: 매거진 레포지토리 생성
  src/main/java/team/seventhmile/tripforp/magazine/Repository.java
Labels: feature

#45 [#44] ✨feat: 매거진 서비스 생성
  src/main/java/team/seventhmile/tripforp/domain/magazine/service/MagazineService.java
Labels: feature

#62 [#61] ✨feat: 매거진 컨트롤러 생성
  src/main/java/team/seventhmile/tripforp/domain/magazine/controller/MagazineController.java
Labels: feature

#65 [#64] ✨feat: 자유게시판 댓글 엔티티 생성
  src/main/java/team/seventhmile/tripforp/domain/free_comment/FreeComment.java
Labels: feature

#72 [#53] ✨ feat: 리뷰 게시글 서비스, 서비스 테스트 코드 구현
  src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
  src/test/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostServiceTest.java
Labels: feature

#75 [#69] ✨feat: 자유게시판 레포지토리 생성 및 패키지 위치 조정
  src/main/java/team/seventhmile/tripforp/domain/free_comment/dto/FreeCommentDto.java
  src/main/java/team/seventhmile/tripforp/domain/free_comment/entity/FreeComment.java
  src/main/java/team/seventhmile/tripforp/domain/free_comment/repository/FreeCommentRepository.java
Labels: bug, feature

#83 [#82] :sparkles: feat: ReviewPostService updateReviewPost plan 구현
  src/main/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostService.java
Labels: feature

#86 [#84] :sparkles: feat: 리뷰 게시글 검색기능 구현(깃 되돌리기 중 날아감)
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryCustom.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryImpl.java
Labels: feature

#81 [#80] ✨feat: 자유게시판 댓글 서비스 구현
  src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
  src/main/java/team/seventhmile/tripforp/domain/magazine/entity/Magazine.java
Labels: feature

#93 [#85] ✨ refactor: RepositoryTest LocalDateTime -> LocalDate 수정
  src/test/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryTest.java
  src/test/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostServiceTest.java
Labels: refactor

#113 [#112] ✨doc: 댓글 서비스 Transactional 추가
  src/main/java/team/seventhmile/tripforp/domain/free_comment/service/FreeCommentService.java
  src/main/java/team/seventhmile/tripforp/domain/review_comment/service/ReviewCommentService.java
Labels: documentation

#118 [#116] :sparkles: feature: 리뷰 게시글 Dto, Entity, RepositoryTest, ServiceTest 수정
  src/main/java/team/seventhmile/tripforp/domain/review_post/dto/ReviewPostDto.java
  src/main/java/team/seventhmile/tripforp/domain/review_post/entity/ReviewPost.java
  src/test/java/team/seventhmile/tripforp/domain/review_post/repository/ReviewPostRepositoryTest.java
  src/test/java/team/seventhmile/tripforp/domain/review_post/service/ReviewPostServiceTest.java
Labels: feature

#119 [#110] :sparkles: feature: 자유 게시글 컨트롤러, 서비스, 리포지토리 (테스트 포함) 구현
  src/main/java/team/seventhmile/tripforp/domain/free_post/controller/FreePostController.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/dto/FreePostDto.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/entity/FreePost.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepository.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryCustom.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryImpl.java
  src/main/java/team/seventhmile/tripforp/domain/free_post/service/FreePostService.java
  src/test/java/team/seventhmile/tripforp/domain/free_post/controller/FreePostControllerTest.java
  src/test/java/team/seventhmile/tripforp/domain/free_post/repository/FreePostRepositoryTest.java
  src/test/java/team/seventhmile/tripforp/domain/free_post/service/FreePostServiceTest.java
Labels: feature
